// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClpGUtNWsu5S-WVgwxykjak8TOptHcM9I',
    appId: '1:769232468896:web:857ec87a2a738bf32442c5',
    messagingSenderId: '769232468896',
    projectId: 'psycare-b901a',
    authDomain: 'psycare-b901a.firebaseapp.com',
    storageBucket: 'psycare-b901a.firebasestorage.app',
    measurementId: 'G-R0DQ3Q1YMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtJykUShe4laKw_N84xaptZCO6odm4bIg',
    appId: '1:769232468896:android:7b176e9bdf558faf2442c5',
    messagingSenderId: '769232468896',
    projectId: 'psycare-b901a',
    storageBucket: 'psycare-b901a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQpUvQRhn7tmdGPZeDBGHxpKzny0dtfIs',
    appId: '1:769232468896:ios:86d6c9ad4f1e8ed92442c5',
    messagingSenderId: '769232468896',
    projectId: 'psycare-b901a',
    storageBucket: 'psycare-b901a.firebasestorage.app',
    iosBundleId: 'com.example.gp1v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQpUvQRhn7tmdGPZeDBGHxpKzny0dtfIs',
    appId: '1:769232468896:ios:86d6c9ad4f1e8ed92442c5',
    messagingSenderId: '769232468896',
    projectId: 'psycare-b901a',
    storageBucket: 'psycare-b901a.firebasestorage.app',
    iosBundleId: 'com.example.gp1v1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClpGUtNWsu5S-WVgwxykjak8TOptHcM9I',
    appId: '1:769232468896:web:15b35fa982a3e4582442c5',
    messagingSenderId: '769232468896',
    projectId: 'psycare-b901a',
    authDomain: 'psycare-b901a.firebaseapp.com',
    storageBucket: 'psycare-b901a.firebasestorage.app',
    measurementId: 'G-VMPMFBNS2R',
  );
}
