// app_localizations.dart
// Static EN/AR localization — no code generation required.

import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      const AppLocalizations(Locale('en'));

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  bool get isAr => locale.languageCode == 'ar';

  static const Map<String, Map<String, String>> _t = {
    'en': {
      'appName': 'PsyCare',
      'appTagline': 'Your Mental Wellness Companion',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'confirmPassword': 'Confirm Password',
      'forgotPassword': 'Forgot Password?',
      'noAccount': "Don't have an account? ",
      'hasAccount': 'Already have an account? ',
      'selectRole': 'I am a...',
      'rolePatient': 'Patient',
      'roleTherapist': 'Therapist',
      'loginSuccess': 'Welcome back!',
      'registerSuccess': 'Account created successfully!',
      'logout': 'Log Out',
      'emailRequired': 'Email is required',
      'emailInvalid': 'Please enter a valid email',
      'passwordRequired': 'Password is required',
      'passwordTooShort': 'Password must be at least 6 characters',
      'nameRequired': 'Name is required',
      'passwordsMismatch': 'Passwords do not match',
      'hello': 'Hello',
      'assessmentSubmitted': 'Assessment Submitted ✓',
      'assessmentPending': 'Assessment Pending',
      'therapistNotified': 'Your therapist has been notified',
      'completeAssessment': 'Complete your assessment to get started',
      'whatToDo': 'What would you like to do?',
      'mentalHealthAssessment': 'Mental Health Assessment',
      'answerQuestions': 'Answer questions about your wellbeing',
      'describeYourFeelings': 'Describe Your Feelings',
      'writeAboutMind': "Write about what's on your mind",
      'aboutPsycare': 'About PsyCare',
      'learnPrivacy': 'Learn how we protect your privacy',
      'talkSomeoneNow': 'Talk to someone now',
      'connectTherapistNow': 'Connect with a therapist right away',
      'availableHours': 'Available 9:00 AM – 10:00 PM',
      'goodDay': 'Good day',
      'totalPatients': 'Total Patients',
      'submitted': 'Submitted',
      'myPatients': 'My Patients',
      'viewAssessments': 'View assessments & AI summaries',
      'aiInsightTip':
          'Use the AI Summarize feature on patient details to get professional insights powered by Groq.',
      'incomingRequests': 'Incoming Requests',
      'patientsWaiting': 'Patients waiting for immediate support',
      'whatBringsYou': 'What brings you here today?',
      'selectAllApply':
          'Select all that apply. This helps us personalize your report.',
      'step1of4': 'Step 1 of 4',
      'selected': 'selected',
      'leave': 'Leave',
      'leaveAssessment': 'Leave assessment?',
      'leaveBody':
          "Your progress will be saved, but the report won't be generated until you finish.",
      'keepGoing': 'Keep going',
      'next': 'Next',
      'youreNotAlone': "You're not alone.",
      'takeYourTime': 'Take your time. What feels right for you right now?',
      'talkNow': 'I need to talk to someone now',
      'talkNowSub': 'Connect with a therapist right away',
      'findTherapist': 'I want to find a therapist',
      'findTherapistSub': 'Browse verified therapists at your own pace',
      'decideLater': "I'll decide later",
      'nextOpenToday': 'today at 9:00 AM',
      'nextOpenTomorrow': 'tomorrow at 9:00 AM',
      'noTherapistsAvailable': 'No therapists available right now',
      'availableFrom':
          "Our support team is available 9:00 AM – 10:00 PM. We'll be here for you",
      'connectingNow': "We're connecting you with\nsomeone now",
      'holdOn':
          "Please hold on — you're not alone.\nA therapist will be with you shortly.",
      'cancel': 'Cancel',
      'yourTherapist': 'Your therapist',
      'sessionActive': 'Session active',
      'sessionEnded': 'Session ended',
      'endSession': 'End',
      'typeMessage': 'Type a message...',
      'bookWithTherapist': 'Book a proper session with this therapist',
      'backToDashboard': 'Back to dashboard',
      'howDidItFeel': 'How did that feel?',
      'bookFollowUp':
          'Would you like to book a proper session with this therapist and continue your journey together?',
      'yesBook': 'Yes, book a session',
      'noDecideLater': "No, I'll decide later",
      'findATherapist': 'Find a Therapist',
      'searchTherapist': 'Search by name or specialization...',
      'noTherapistsFound': 'No therapists found.',
      'bookSession': 'Book a Session',
      'preferredSessionType': 'Preferred session type',
      'chatSession': 'Chat',
      'videoSession': 'Video Call',
      'inPersonSession': 'In-Person',
      'dataSharingConsent': 'Data sharing consent',
      'consentBody':
          'By confirming this booking, you agree to share your assessment data and AI-generated report with',
      'consentBody2':
          'This information helps your therapist prepare and provide you with the most relevant support from the very first session.',
      'consentCheckbox':
          'I understand and consent to my assessment data being shared with this therapist.',
      'confirmBooking': 'Confirm Booking Request',
      'requestSent': 'Request Sent!',
      'bookingConfirmed': "Your booking request has been sent to",
      'bookingConfirmed2': "You'll hear back once they confirm.",
      'incomingTitle': 'Incoming Requests',
      'incomingSubtitle':
          'Patients in your queue waiting for immediate support.',
      'noPendingRequests': 'No pending requests',
      'pendingEmpty': "When a patient needs immediate help,\nthey'll appear here.",
      'assessmentSummary': 'Assessment summary',
      'acceptConnect': 'Accept & Connect',
      'justNow': 'Just now',
      'minuteAgo': '1 minute ago',
      'minutesAgo': 'minutes ago',
      'hoursAgo': 'h ago',
      'settings': 'Settings',
      'profile': 'Profile',
      'language': 'Language',
      'languageSubtitle': 'Switch between English and Arabic',
      'availability': 'Availability',
      'onShift': 'On Shift',
      'onShiftSub': "You're currently available to patients",
      'availableForImmediate': 'Available for Immediate Chat',
      'availableForImmediateSub':
          'Accept urgent requests from waiting patients',
      'account': 'Account',
      'resetPassword': 'Reset Password',
      'resetPasswordSub': "We'll send a reset link to your email",
      'app': 'App',
      'privacyPolicy': 'Privacy Policy',
      'dangerZone': 'Danger Zone',
      'signOut': 'Sign Out',
      'deleteAccount': 'Delete Account',
      'deleteAccountSub': 'This action cannot be undone',
      'version': 'PsyCare v1.0.0',
      'deleteConfirmTitle': 'Delete account?',
      'deleteConfirmBody':
          'All your data will be permanently deleted. This cannot be undone.',
      'delete': 'Delete',
      'close': 'Close',
      'resetLinkSent': 'Reset link sent to',
      'failedTo': 'Failed:',
      'failedDelete': 'Failed to delete:',
      'loading': 'Loading...',
      'error': 'Something went wrong',
      'retry': 'Retry',
      'save': 'Save',
      'gotIt': 'Got it',
      'crisisTitle': "You're not alone — help is available",
      'crisisBody':
          "We noticed you may be going through something very difficult. "
          "Please reach out to a crisis line right now — trained counsellors are ready to listen, 24/7.",
      'crisisIntlLabel': 'International (Befrienders)',
      'crisisIntlNumber': '+1-800-273-8255',
      'crisisLocalLabel': 'Saudi Arabia',
      'crisisLocalNumber': '920033360',
      'crisisEmergencyLabel': 'Emergency services',
      'crisisEmergencyNumber': '911 / 999',
      'sessionRequests': 'Session Requests',
      'sessionRequestsSubtitle': 'Patients requesting scheduled sessions',
      'noSessionRequests': 'No session requests',
      'noSessionRequestsBody': 'When a patient books a session with you,\nit will appear here.',
      'acceptBooking': 'Accept',
      'decline': 'Decline',
      'bookingAcceptedSnack': 'Booking confirmed.',
      'bookingDeclinedSnack': 'Booking declined.',
      // Chatbot
      'chatbotInitError': 'Could not start the session. Please try again.',
      'talkToAI': 'Talk to AI 💙',
      'talkToAISubtitle': 'A private space to express yourself',
      'chatbotTitle': 'PsyCare Chat 💙',
      'chatbotSubtitle': 'This is a safe space',
      'chatbotInputHint': 'Type a message... 💙',
      'chatbotLimitTitle': "You've shared a lot today, and I've really been here with you. 💙",
      'chatbotLimitBody': 'Sometimes talking to a real person can make all the difference. Would you like to connect with your therapist directly?',
      'chatbotLimitYes': 'Yes, open chat with therapist',
      'chatbotLimitNo': "I'm okay for now, thank you",
      'endChatTitle': 'End this session?',
      'endChatBody': 'Your conversation is saved. You can continue where you left off next time.',
      'stayHere': 'Stay here',
      'endChat': 'End session',
      // Red flag screen (therapist)
      'redFlagAlertsTitle': 'Patient Alerts',
      'redFlagAlertsSubtitle': 'Messages that may need your attention',
      'noRedFlagAlerts': 'All clear',
      'noRedFlagAlertsBody': 'No patient alerts at this time.',
      'viewContext': 'View context',
      'conversationContext': 'Conversation context',
      'aiSummaryLabel': 'AI Summary',
      'markAsRead': 'Mark as read',
      'bookingStatusPending': 'Booking Pending',
      'bookingStatusConfirmed': 'Booking Confirmed',
      'bookingStatusDeclined': 'Booking Declined',
      'bookingStatusCancelledPatient': 'You Cancelled',
      'bookingStatusCancelledTherapist': 'Therapist Cancelled',
      'bookingStatusRescheduleRequested': 'Reschedule Requested',
      'cancelBooking': 'Cancel Booking',
      'cancelBookingTitle': 'Cancel this booking?',
      'cancelBookingHint': 'Reason (optional)',
      'cancelBookingConfirm': 'Yes, Cancel',
      'requestReschedule': 'Request Reschedule',
      'rescheduleTitle': 'Request a Reschedule',
      'rescheduleHint': 'Preferred new time or note...',
      'rescheduleConfirm': 'Send Request',
      'rescheduleNote': 'Reschedule note',
      'confirmReschedule': 'Confirm Reschedule',
      'bookingCancelledSnack': 'Booking cancelled.',
      'rescheduleSentSnack': 'Reschedule request sent.',
      'rescheduleConfirmedSnack': 'Reschedule confirmed.',
      'confirmedSessions': 'Confirmed Sessions',
      'noConfirmedSessions': 'No confirmed sessions yet',
      'noConfirmedSessionsBody': 'Accepted bookings will appear here.',
      'pendingRequests': 'Pending Requests',
      'myMessages': 'My Messages',
      'myMessagesSubtitle': 'Your chat sessions with therapists',
      'noSessions': 'No sessions yet',
      'noSessionsBody': 'Your chat sessions will appear here.',
      'noSummaryAvailable': 'No summary available',
      'patientSession': 'Session with Patient',
      'therapistSession': 'Session with Therapist',
      'resumeSession': 'Resume Chat',
      'viewSession': 'View Chat',
      'messageYourTherapist': 'Message Your Therapist',
      'tapToChat': 'Tap to open your chat',

      // ── Volunteer strings ──────────────────────────────────────────────────
      'volunteerThanks': 'Thank you for making a difference 💙',
      'volunteerHrs': 'Hrs Volunteered',
      'patients': 'Patients',
      'rating': 'Rating',
      'myConnections': 'My Connections',
      'browseVolunteers': 'Browse Volunteers',
      'browseVolunteersSub': 'Connect with a volunteer student',
      'myVolunteerConnections': 'My Volunteer Connections',
      'myVolunteerConnectionsSub': 'Chat with your volunteers',
      'editProfile': 'Edit Profile',
      'activeConnections': 'Active Connections',
      'noActiveConnections': 'No active connections yet',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'openChat': 'Open Chat',
      'viewProfile': 'View Profile',
      'pastConnections': 'Past Connections',
      'noConnectionsYet': 'No connections yet',
      'ended': 'Ended',
      'findCompanion': 'Find a Companion',
      'findCompanionSub': 'Connect with a volunteer student',
      'volunteerInfoBanner':
          'Our volunteers are psychology, medicine and social work students who offer friendly support. They are not therapists.',
      'noVolunteersAvailable': 'No volunteers available right now',
      'about': 'About',
      'noBio': 'No bio added yet.',
      'newVolunteer': 'New',
      'reviews': 'reviews',
      'connectWith': 'Connect with',
      'connectConfirmTitle': 'Connect with Volunteer?',
      'connectConfirmBody':
          "You're about to connect with {name}. This will open a private chat.",
      'connectConfirmYes': 'Connect!',
      'notNow': 'Not now',
      'volunteerSetupTitle': 'Set Up Your Profile',
      'volunteerSetupSubtitle':
          'Help patients find the right companion for them',
      'university': 'University',
      'universityHint': 'e.g. King Saud University',
      'specialization': 'Specialization',
      'yearOfStudy': 'Year of Study',
      'bio': 'Short Bio',
      'bioHint': 'Tell patients a bit about yourself...',
      'availableToConnect': 'I am available to connect with patients',
      'startVolunteering': 'Start Volunteering 💙',
      'fieldRequired': 'This field is required',
      'suggestMeetup': 'Suggest a Meetup',
      'meetupPlace': 'Place',
      'meetupPlaceHint': 'e.g. Campus café',
      'meetupNote': 'Note',
      'meetupNoteHint': 'Optional note...',
      'sendSuggestion': 'Send Suggestion',
      'meetupSuggestion': '📅 Meetup Suggestion',
      'meetupAgreed': '✅ Sounds good!',
      'meetupDeclined': '❌ Maybe another time',
      'endConnection': 'End Connection',
      'endConnectionConfirm':
          'Are you sure you want to end this connection?',
      'chatWithPatient': 'Chat with Patient',
      'chatWithVolunteer': 'Chat with Volunteer',
      'awaitingResponse': 'Awaiting response...',
      'noMessagesYet': 'No messages yet. Say hello! 👋',

      // ── Request flow strings ───────────────────────────────────────────────
      'browsePatients': 'Browse Patients',
      'browsePatientsSub': 'Send connection requests to patients',
      'sendRequest': 'Send Request',
      'requestPending': 'Awaiting Response',
      'acceptRequest': 'Accept 💙',
      'declineRequest': 'Decline',
      'volunteerRequests': 'Volunteer Requests',
      'noIncomingRequests': 'No incoming requests',
      'noPatientsFound': 'No patients found',
      'noVolunteersFound': 'No volunteers found',
      'connected': 'Connected',
      'requestDeclined': 'Declined',
      'myVolunteerFriends': 'My Volunteer Friends',
      'myVolunteerFriendsSub': 'Your connected volunteers',
      'messageVolunteer': 'Message',
    },
    'ar': {
      'appName': 'PsyCare',
      'appTagline': 'رفيقك للصحة النفسية',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'fullName': 'الاسم الكامل',
      'confirmPassword': 'تأكيد كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'noAccount': 'ليس لديك حساب؟ ',
      'hasAccount': 'لديك حساب بالفعل؟ ',
      'selectRole': 'أنا...',
      'rolePatient': 'مريض',
      'roleTherapist': 'معالج نفسي',
      'loginSuccess': 'مرحباً بعودتك!',
      'registerSuccess': 'تم إنشاء الحساب بنجاح!',
      'logout': 'تسجيل الخروج',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'emailInvalid': 'يرجى إدخال بريد إلكتروني صحيح',
      'passwordRequired': 'كلمة المرور مطلوبة',
      'passwordTooShort': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'nameRequired': 'الاسم مطلوب',
      'passwordsMismatch': 'كلمات المرور غير متطابقة',
      'hello': 'مرحباً',
      'assessmentSubmitted': 'تم تقديم التقييم ✓',
      'assessmentPending': 'التقييم معلق',
      'therapistNotified': 'تم إبلاغ معالجك',
      'completeAssessment': 'أكمل تقييمك للبدء',
      'whatToDo': 'ماذا تريد أن تفعل؟',
      'mentalHealthAssessment': 'تقييم الصحة النفسية',
      'answerQuestions': 'أجب على أسئلة حول حالتك',
      'describeYourFeelings': 'صف مشاعرك',
      'writeAboutMind': 'اكتب عما يدور في ذهنك',
      'aboutPsycare': 'عن PsyCare',
      'learnPrivacy': 'اعرف كيف نحمي خصوصيتك',
      'talkSomeoneNow': 'تحدث مع شخص الآن',
      'connectTherapistNow': 'تواصل مع معالج نفسي فوراً',
      'availableHours': 'متاح 9:00 صباحاً – 10:00 مساءً',
      'goodDay': 'يوم سعيد',
      'totalPatients': 'إجمالي المرضى',
      'submitted': 'المُقدَّم',
      'myPatients': 'مرضاي',
      'viewAssessments': 'عرض التقييمات وملخصات الذكاء الاصطناعي',
      'aiInsightTip':
          'استخدم ميزة تلخيص الذكاء الاصطناعي في تفاصيل المريض للحصول على رؤى مهنية مدعومة بـ Groq.',
      'incomingRequests': 'الطلبات الواردة',
      'patientsWaiting': 'مرضى ينتظرون دعماً فورياً',
      'whatBringsYou': 'ما الذي أحضرك إلى هنا اليوم؟',
      'selectAllApply': 'اختر جميع ما ينطبق. سيساعدنا ذلك في تخصيص تقريرك.',
      'step1of4': 'الخطوة 1 من 4',
      'selected': 'مُختار',
      'leave': 'مغادرة',
      'leaveAssessment': 'هل تريد مغادرة التقييم؟',
      'leaveBody':
          'سيتم حفظ تقدمك، لكن لن يتم إنشاء التقرير حتى تنتهي.',
      'keepGoing': 'استمر',
      'next': 'التالي',
      'youreNotAlone': 'أنت لست وحدك.',
      'takeYourTime': 'خذ وقتك. ما الذي يناسبك الآن؟',
      'talkNow': 'أحتاج للتحدث مع شخص الآن',
      'talkNowSub': 'تواصل مع معالج نفسي فوراً',
      'findTherapist': 'أريد إيجاد معالج نفسي',
      'findTherapistSub': 'تصفح المعالجين المعتمدين بوتيرتك',
      'decideLater': 'سأقرر لاحقاً',
      'nextOpenToday': 'اليوم الساعة 9:00 صباحاً',
      'nextOpenTomorrow': 'غداً الساعة 9:00 صباحاً',
      'noTherapistsAvailable': 'لا يوجد معالجون متاحون الآن',
      'availableFrom':
          'فريق الدعم متاح من 9:00 صباحاً حتى 10:00 مساءً. سنكون هنا من أجلك',
      'connectingNow': 'نقوم بتوصيلك\nبشخص الآن',
      'holdOn': 'يرجى الانتظار — أنت لست وحدك.\nسيكون المعالج معك قريباً.',
      'cancel': 'إلغاء',
      'yourTherapist': 'معالجك',
      'sessionActive': 'الجلسة نشطة',
      'sessionEnded': 'انتهت الجلسة',
      'endSession': 'إنهاء',
      'typeMessage': 'اكتب رسالة...',
      'bookWithTherapist': 'احجز جلسة رسمية مع هذا المعالج',
      'backToDashboard': 'العودة إلى لوحة التحكم',
      'howDidItFeel': 'كيف شعرت؟',
      'bookFollowUp':
          'هل تريد حجز جلسة رسمية مع هذا المعالج ومواصلة رحلتك معاً؟',
      'yesBook': 'نعم، احجز جلسة',
      'noDecideLater': 'لا، سأقرر لاحقاً',
      'findATherapist': 'ابحث عن معالج نفسي',
      'searchTherapist': 'ابحث بالاسم أو التخصص...',
      'noTherapistsFound': 'لا يوجد معالجون.',
      'bookSession': 'حجز جلسة',
      'preferredSessionType': 'نوع الجلسة المفضل',
      'chatSession': 'محادثة',
      'videoSession': 'مكالمة مرئية',
      'inPersonSession': 'حضورياً',
      'dataSharingConsent': 'موافقة على مشاركة البيانات',
      'consentBody':
          'بتأكيد هذا الحجز، توافق على مشاركة بيانات تقييمك وتقريرك مع',
      'consentBody2':
          'تساعد هذه المعلومات معالجك على الاستعداد وتقديم الدعم الأنسب لك من الجلسة الأولى.',
      'consentCheckbox':
          'أفهم وأوافق على مشاركة بيانات تقييمي مع هذا المعالج.',
      'confirmBooking': 'تأكيد طلب الحجز',
      'requestSent': 'تم إرسال الطلب!',
      'bookingConfirmed': 'تم إرسال طلب حجزك إلى',
      'bookingConfirmed2': 'ستتلقى رداً بمجرد تأكيده.',
      'incomingTitle': 'الطلبات الواردة',
      'incomingSubtitle': 'المرضى في قائمة الانتظار يحتاجون دعماً فورياً.',
      'noPendingRequests': 'لا توجد طلبات معلقة',
      'pendingEmpty': 'عندما يحتاج مريض مساعدة فورية،\nسيظهر هنا.',
      'assessmentSummary': 'ملخص التقييم',
      'acceptConnect': 'قبول والاتصال',
      'justNow': 'الآن',
      'minuteAgo': 'منذ دقيقة',
      'minutesAgo': 'دقائق مضت',
      'hoursAgo': 'ساعة مضت',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'language': 'اللغة',
      'languageSubtitle': 'التبديل بين الإنجليزية والعربية',
      'availability': 'التوفر',
      'onShift': 'في الوردية',
      'onShiftSub': 'أنت متاح حالياً للمرضى',
      'availableForImmediate': 'متاح للمحادثة الفورية',
      'availableForImmediateSub': 'قبول الطلبات العاجلة من المرضى المنتظرين',
      'account': 'الحساب',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'resetPasswordSub': 'سنرسل رابط إعادة التعيين إلى بريدك الإلكتروني',
      'app': 'التطبيق',
      'privacyPolicy': 'سياسة الخصوصية',
      'dangerZone': 'منطقة الخطر',
      'signOut': 'تسجيل الخروج',
      'deleteAccount': 'حذف الحساب',
      'deleteAccountSub': 'لا يمكن التراجع عن هذا الإجراء',
      'version': 'PsyCare v1.0.0',
      'deleteConfirmTitle': 'حذف الحساب؟',
      'deleteConfirmBody':
          'سيتم حذف جميع بياناتك بشكل دائم. لا يمكن التراجع عن هذا.',
      'delete': 'حذف',
      'close': 'إغلاق',
      'resetLinkSent': 'تم إرسال رابط إعادة التعيين إلى',
      'failedTo': 'فشل:',
      'failedDelete': 'فشل الحذف:',
      'loading': 'جارٍ التحميل...',
      'error': 'حدث خطأ ما',
      'retry': 'إعادة المحاولة',
      'save': 'حفظ',
      'gotIt': 'حسناً',
      'crisisTitle': 'لست وحدك — المساعدة متاحة',
      'crisisBody':
          'لاحظنا أنك قد تمر بشيء صعب جداً. '
          'يُرجى التواصل مع خط أزمات الآن — متخصصون مدربون على الاستماع إليك، على مدار الساعة.',
      'crisisIntlLabel': 'دولي (بيفريندرز)',
      'crisisIntlNumber': '+1-800-273-8255',
      'crisisLocalLabel': 'المملكة العربية السعودية',
      'crisisLocalNumber': '920033360',
      'crisisEmergencyLabel': 'الطوارئ',
      'crisisEmergencyNumber': '911 / 999',
      'sessionRequests': 'طلبات الجلسات',
      'sessionRequestsSubtitle': 'مرضى يطلبون جلسات مجدولة',
      'noSessionRequests': 'لا توجد طلبات جلسات',
      'noSessionRequestsBody': 'عندما يحجز مريض جلسة معك،\nستظهر هنا.',
      'acceptBooking': 'قبول',
      'decline': 'رفض',
      'bookingAcceptedSnack': 'تم تأكيد الحجز.',
      'bookingDeclinedSnack': 'تم رفض الحجز.',
      // Chatbot
      'chatbotInitError': 'تعذّر بدء الجلسة. يرجى المحاولة مرة أخرى.',
      'talkToAI': 'تحدث مع الذكاء الاصطناعي 💙',
      'talkToAISubtitle': 'مساحة خاصة للتعبير عن نفسك',
      'chatbotTitle': 'محادثة PsyCare 💙',
      'chatbotSubtitle': 'هذا مكان آمن',
      'chatbotInputHint': 'اكتب رسالة... 💙',
      'chatbotLimitTitle': 'لقد شاركت الكثير اليوم، وكنت معك طوال الوقت. 💙',
      'chatbotLimitBody': 'في بعض الأحيان التحدث مع شخص حقيقي يصنع الفرق. هل تريد التواصل مع معالجك مباشرة؟',
      'chatbotLimitYes': 'نعم، افتح المحادثة مع المعالج',
      'chatbotLimitNo': 'أنا بخير الآن، شكراً',
      'endChatTitle': 'إنهاء هذه الجلسة؟',
      'endChatBody': 'محادثتك محفوظة. يمكنك الاستمرار من حيث توقفت في المرة القادمة.',
      'stayHere': 'ابقَ هنا',
      'endChat': 'إنهاء الجلسة',
      // Red flag screen (therapist)
      'redFlagAlertsTitle': 'تنبيهات المرضى',
      'redFlagAlertsSubtitle': 'رسائل قد تحتاج إلى انتباهك',
      'noRedFlagAlerts': 'كل شيء على ما يرام',
      'noRedFlagAlertsBody': 'لا توجد تنبيهات للمرضى في الوقت الحالي.',
      'viewContext': 'عرض السياق',
      'conversationContext': 'سياق المحادثة',
      'aiSummaryLabel': 'ملخص الذكاء الاصطناعي',
      'markAsRead': 'تحديد كمقروء',
      'bookingStatusPending': 'الحجز قيد الانتظار',
      'bookingStatusConfirmed': 'تم تأكيد الحجز',
      'bookingStatusDeclined': 'تم رفض الحجز',
      'bookingStatusCancelledPatient': 'قمت بالإلغاء',
      'bookingStatusCancelledTherapist': 'أُلغي من قِبل المعالج',
      'bookingStatusRescheduleRequested': 'طُلب إعادة الجدولة',
      'cancelBooking': 'إلغاء الحجز',
      'cancelBookingTitle': 'إلغاء هذا الحجز؟',
      'cancelBookingHint': 'السبب (اختياري)',
      'cancelBookingConfirm': 'نعم، إلغاء',
      'requestReschedule': 'طلب إعادة جدولة',
      'rescheduleTitle': 'طلب إعادة جدولة',
      'rescheduleHint': 'الوقت المفضل أو ملاحظة...',
      'rescheduleConfirm': 'إرسال الطلب',
      'rescheduleNote': 'ملاحظة إعادة الجدولة',
      'confirmReschedule': 'تأكيد إعادة الجدولة',
      'bookingCancelledSnack': 'تم إلغاء الحجز.',
      'rescheduleSentSnack': 'تم إرسال طلب إعادة الجدولة.',
      'rescheduleConfirmedSnack': 'تم تأكيد إعادة الجدولة.',
      'confirmedSessions': 'الجلسات المؤكدة',
      'noConfirmedSessions': 'لا توجد جلسات مؤكدة بعد',
      'noConfirmedSessionsBody': 'ستظهر الحجوزات المقبولة هنا.',
      'pendingRequests': 'الطلبات المعلقة',
      'myMessages': 'رسائلي',
      'myMessagesSubtitle': 'جلسات المحادثة مع المعالجين',
      'noSessions': 'لا توجد جلسات بعد',
      'noSessionsBody': 'ستظهر جلسات المحادثة هنا.',
      'noSummaryAvailable': 'لا يوجد ملخص',
      'patientSession': 'جلسة مع مريض',
      'therapistSession': 'جلسة مع معالج',
      'resumeSession': 'استئناف المحادثة',
      'viewSession': 'عرض المحادثة',
      'messageYourTherapist': 'راسل معالجك',
      'tapToChat': 'اضغط لفتح المحادثة',

      // ── Volunteer strings ──────────────────────────────────────────────────
      'volunteerThanks': 'شكراً لأنك تصنع فارقاً 💙',
      'volunteerHrs': 'ساعات التطوع',
      'patients': 'المرضى',
      'rating': 'التقييم',
      'myConnections': 'اتصالاتي',
      'browseVolunteers': 'تصفح المتطوعين',
      'browseVolunteersSub': 'تواصل مع طالب متطوع',
      'myVolunteerConnections': 'اتصالاتي مع المتطوعين',
      'myVolunteerConnectionsSub': 'تحدث مع متطوعيك',
      'editProfile': 'تعديل الملف',
      'activeConnections': 'الاتصالات النشطة',
      'noActiveConnections': 'لا توجد اتصالات نشطة حتى الآن',
      'available': 'متاح',
      'unavailable': 'غير متاح',
      'openChat': 'فتح المحادثة',
      'viewProfile': 'عرض الملف',
      'pastConnections': 'الاتصالات السابقة',
      'noConnectionsYet': 'لا توجد اتصالات بعد',
      'ended': 'منتهية',
      'findCompanion': 'ابحث عن رفيق',
      'findCompanionSub': 'تواصل مع طالب متطوع',
      'volunteerInfoBanner':
          'متطوعونا طلاب في علم النفس والطب والعمل الاجتماعي يقدمون دعماً ودياً. هم ليسوا معالجين نفسيين.',
      'noVolunteersAvailable': 'لا يوجد متطوعون متاحون الآن',
      'about': 'عن',
      'noBio': 'لم تتم إضافة نبذة بعد.',
      'newVolunteer': 'جديد',
      'reviews': 'تقييمات',
      'connectWith': 'تواصل مع',
      'connectConfirmTitle': 'التواصل مع المتطوع؟',
      'connectConfirmBody':
          'أنت على وشك التواصل مع {name}. سيفتح هذا محادثة خاصة.',
      'connectConfirmYes': 'تواصل!',
      'notNow': 'ليس الآن',
      'volunteerSetupTitle': 'إعداد ملفك الشخصي',
      'volunteerSetupSubtitle': 'ساعد المرضى في إيجاد الرفيق المناسب',
      'university': 'الجامعة',
      'universityHint': 'مثال: جامعة الملك سعود',
      'specialization': 'التخصص',
      'yearOfStudy': 'سنة الدراسة',
      'bio': 'نبذة مختصرة',
      'bioHint': 'أخبر المرضى قليلاً عن نفسك...',
      'availableToConnect': 'أنا متاح للتواصل مع المرضى',
      'startVolunteering': 'ابدأ التطوع 💙',
      'fieldRequired': 'هذا الحقل مطلوب',
      'suggestMeetup': 'اقترح لقاءً',
      'meetupPlace': 'المكان',
      'meetupPlaceHint': 'مثال: كافيه الحرم الجامعي',
      'meetupNote': 'ملاحظة',
      'meetupNoteHint': 'ملاحظة اختيارية...',
      'sendSuggestion': 'إرسال الاقتراح',
      'meetupSuggestion': '📅 اقتراح لقاء',
      'meetupAgreed': '✅ يبدو رائعاً!',
      'meetupDeclined': '❌ ربما في وقت آخر',
      'endConnection': 'إنهاء الاتصال',
      'endConnectionConfirm': 'هل أنت متأكد أنك تريد إنهاء هذا الاتصال؟',
      'chatWithPatient': 'محادثة المريض',
      'chatWithVolunteer': 'محادثة المتطوع',
      'awaitingResponse': 'في انتظار الرد...',
      'noMessagesYet': 'لا رسائل بعد. قل مرحبا! 👋',

      // ── Request flow strings ───────────────────────────────────────────────
      'browsePatients': 'تصفح المرضى',
      'browsePatientsSub': 'أرسل طلبات اتصال للمرضى',
      'sendRequest': 'إرسال طلب',
      'requestPending': 'في انتظار الرد',
      'acceptRequest': 'قبول 💙',
      'declineRequest': 'رفض',
      'volunteerRequests': 'طلبات المتطوعين',
      'noIncomingRequests': 'لا توجد طلبات واردة',
      'noPatientsFound': 'لا يوجد مرضى',
      'noVolunteersFound': 'لا يوجد متطوعون',
      'connected': 'متصل',
      'requestDeclined': 'مرفوض',
      'myVolunteerFriends': 'أصدقاء المتطوعين',
      'myVolunteerFriendsSub': 'المتطوعون المتصلون بك',
      'messageVolunteer': 'رسالة',
    },
  };

  String tr(String key) =>
      (_t[locale.languageCode] ?? _t['en']!)[key] ?? _t['en']![key] ?? key;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key) => AppLocalizations.of(this).tr(key);
}
